#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>

## launch wofi with alt config


if [[ ! `pidof rofi` ]]; then
	rofi --show drun --prompt 'Search...'
else
	pkill rofi
fi
