services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
        #- PLEX_CLAIM= #optional
    volumes:
      - ${HOME}/plex:/config
      - ${MEDIA}/tv:/tv
      - ${MEDIA}/movies:/movies
    restart: unless-stopped
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
        #- JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - ${HOME}/jellyfin/library:/config
      - ${HOME}/jellyfin/tvseries:/data/tvshows
      - ${HOME}/jellyfin/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    volumes:
      - ${HOME}/qbittorrent/config:/config
      - ${DOWNLOADS}:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${HOME}/overseerr/config:/config
    ports:
      - 5055:5055
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${HOME}/radarr/data:/config
      - ${MEDIA}/movies:/movies #optional
      - ${DOWNLOADS}:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - ${HOME}/deluge/config:/config
      - ${DOWNLOADS}:/downloads
    ports:
      - 8112:8112
      - 6882:6881
      - 6882:6881/udp
      - 58846:58846 #optional
    restart: unless-stopped
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - ${HOME}/jackett:/config
      - ${DOWNLOADS}:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${HOME}/sonarr:/config
      - ${MEDIA}/tv:/tv #optional
      - ${DOWNLOADS}:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
