#!/bin/bash

echo "Do you want to install dependencies?"
echo -n "y/n: "
read REPLAY

if [ "$REPLAY" == "y" ] 
then
        zypper -n install ninja libtool autoconf automake cmake gcc-c++ gettext-tools git zsh tmux curl
fi

# neovim
cd
NVIM_DIR="~/neovim"

function install_nvim () {
        cd $NVIM_DIR
        make CMAKE_BUILD_TYPE=Release
        make CMAKE_INSTALL_PREFIX=$HOME/local/nvim install
}

if  command -v nvim &> /dev/null
then
        echo "Do you want to update the neovim file?"
        echo -n "y/n: "
        read -r
        if [ "$REPLAY" == "y" ] 
        then
                git pull && install_nvim
        fi
else
        echo "Installing  fresh nvim"
        git clone https://github.com/neovim/neovim
        install_nvim
fi


# vim plug
VIMPLUG_DIR="$HOME/.local/share/nvim/site/autoload/plug.vim"

function install_vim_plug () {
        sh -c 'curl -fLo $VIMPLUG_DIR --create-dirs \
                https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
}

if [ -f "$VIMPLUG_DIR" ] 
then
        echo "Do you want to update the vim plug ?"
        echo -n "y/n: "
        read -r
        if [ "$REPLAY" == "y" ] 
        then
                install_vim_plug
        fi
else
        echo "Installing  fresh vim plug"
        install_vim_plug
fi

# oh-my-zsh 
OHMYZSH_DIR="$HOME/.oh-my-zsh/"
if [ ! -d "$OHMYZSH_DIR" ] 
then
        cd
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
fi

# oh-my-tmux
OHMYTMUX_DIR="$HOME/.tmux/"
if [ ! -d "$OHMYTMUX_DIR" ] 
then
cd
        git clone https://github.com/gpakosz/.tmux.git
        ln -s -f .tmux/.tmux.conf
        cp .tmux/.tmux.conf.local .
fi

# oacs dot fiels
echo "Do you want to update the dotfiles?"
echo -n "y/n: "
read -r
if [ "$REPLAY" == "y" ] 
then
        bash load
fi

#nvm
if  command -v nvm &> /dev/null
then
        echo "Installing  fresh nvm"
        #curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
else
        echo "Nvm is already installed"
fi
