#!/usr/bin/env bash
mkdir -p /home/oacs/.config/nvim
mkdir -p /home/oacs/.config/nvim/plugin
mkdir -p /home/oacs/.config/nvim/after/plugin
mkdir -p /home/oacs/.config/nvim/lua
mkdir -p /home/oacs/.config/nvim/lua/plugin

# link wholesale
for f in `find . -regex "\.\/nvim\/.*\..*" | sed "s/\.\///g"`; do
    rm -rf /home/oacs/.config/$f
    ln -sf /home/oacs/.dotfiles/$f /home/oacs/.config/$f
    echo /home/oacs/.config/$f
done

rm -rf /home/oacs/tmux.conf.local
ln -s /home/oacs/.dotfiles/.tmux.conf.local /home/oacs/.tmux.conf.local

