#!/usr/bin/env bash
mkdir -p ~/.config/nvim/plugin
mkdir -p ~/.config/nvim/after/plugin
mkdir -p ~/.config/nvim/lua
mkdir -p ~/.config/nvim/lua/plugin

# link wholesale
for f in `find . -regex "\.\/nvim\/.*\..*"`; do
    rm -rf ~/.config/$f
    ln -s ~/dotfiles/$f ~/.config/$f
    echo ~/.config/$f
done

rm -rf ~/.tmux.conf.local
ln -s ~/dotfiles/.tmux.conf.local ~/.tmux.conf.local

