#!/usr/bin/env bash
mkdir -p /home/oacs/.config/nvim/plugin
mkdir -p /home/oacs/.config/nvim/after/plugin
mkdir -p /home/oacs/.config/nvim/lua/plugin

# link wholesale
for f in `find . -regex "\.\/nvim\/.*\.lua" | sed "s/\.\///g"`; do
    rm -rf /home/oacs/.config/$f
    ln -sf /home/oacs/dev/dotfiles/$f /home/oacs/.config/$f
    echo /home/oacs/.config/$f
done

ln -sf /home/oacs/dev/dotfiles/.tmux.conf.local /home/oacs/.tmux.conf.local
ln -sf /home/oacs/dev/dotfiles/ta /home/oacs/bin
ln -sf /home/oacs/dev/dotfiles/ta /usr/local/bin/ta
