#!/bin/bash
WORK_DIR=/home/oacs/dev
LOCAL_DIR=/home/oacs/local
mkdir -p $LOCAL_DIR
cd $LOCAL_DIR
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip awscliv2.zip
sudo ./aws/install
mkdir -p $WORK_DIR
cd $WORK_DIR

git clone git@github.com:Moregidge/moregidge-backend.git back
git clone git@github.com:Moregidge/moregidge-frontend.git front
git clone git@github.com:Moregidge/admin-portal.git adtal
git clone git@github.com:Moregidge/pdf-genie.git genie

aws configure

cd back
npm i
npm run credentials:setup:test

cd ../front
npm i

cd ../adtal
npm i
cd backend
npm i
npm run credentials:setup:test
cd ../frontend
npm i

