#!/usr/bin/env bash

PERSONAL_SESSION="oacs"
DOTFILE="~/dotfiles"
ADTAL="~/dev/adtal"
ADTAL_FRONT="~/dev/adtal/frontend"
ADTAL_BACK="~/dev/adtal/backend"
BACK="~/dev/back"
FRONT="~/dev/front"
SANDBOX="~/dev/playground"

createWindow() {
    session=$1
    window=$2
    shift
    shift
    hasWindow=$(tmux list-windows -t $session | grep "$window")
    if [ -z "$hasWindow" ]; then
        cmd="tmux neww -t $session: -n $window -d"
        if [ $# -gt 0 ]; then
            cmd="$cmd $@"
        fi
        echo "Creating Window(\"$hasWindow\"): $cmd"
        eval $cmd
    fi
}

createSession() {
    session=$1
    window=$2
    shift
    shift
    cmd="tmux new -s $session -d -n $window $@ > /dev/null 2>&1"

    echo "Creating Session: $cmd"
    eval $cmd
}

attachSession() {
    session=$1
    eval "tmux attach -t $session"
}

while [ "$#" -gt 0 ]; do
    curr=$1
    shift

    case "$curr" in
    "-a")
        echo $ADTAL
        createSession adtal adtal -c $ADTAL  " nvim ."
        createWindow adtal frontA -c $ADTAL_FRONT " npm run start"
        createWindow adtal backA -c $ADTAL_BACK " npm run start:ubuntu"
        createWindow adtal sandbox -c $SANDBOX " nvim ."
        attachSession adtal
        ;;
    "-b")
        createSession backend back -c $BACK " nvim ."
        createWindow backend console -c $BACK " npm run start:ubuntu"
        attachSession back
        ;;

    "-f")
        createSession frontend primary
        createWindow frontend front -c $FRONT
        createWindow frontend console -c $FRONT "npm run start:ubuntu"
        attachSession front
        ;;

    "-s")
        createSession $PERSONAL_SESSION primary -c "~"
        createWindow $PERSONAL_SESSION oacs -c "~"
        createWindow $PERSONAL_SESSION dotfiles -c $SANDBOX
        attachSession oacs
        ;;

    *) echo "Unavailable command... $curr"
    esac
done
