#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xrandr --output HDMI-0 --primary --mode 1920x1080 --pos 1920x0 --rotate normal --output eDP1 --mode 1920x1080 --pos 0x0 --rotate normal --output VIRTUAL1 --off

bspc monitor ^1 -s ^2 
bspc monitor HDMI-0 -d I II III IV V
bspc monitor eDP1 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12
bspc config window_gap          12
bspc config top_padding         25

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Brave-browser desktop='^1'
bspc rule -a Slack desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

feh --bg-scale ~/Pictures/Wallpapers/wallhaven-2839em_1920x1080.png

polybar left & polybar right & polybar mid
