- name: Create ~/.config
  file:
    path: ~/.config
    state: directory

- name: Create ~/.local/share/applications
  file:
    path: ~/.local/share/applications
    state: directory

- name: Find .config files
  find:
    paths: ~/.dotfiles/config/
    recurse: no
    file_type: any
    hidden: yes
  register: dot_config

- name: ~/.config/
  file:
    src: "{{item.path}}"
    dest: "~/.config/{{item.path | basename}}"
    state: link
  loop: "{{ dot_config.files }}"
  loop_control:
    label: "~/.config/{{item.path | basename}}"

- name: .bashrc
  copy:
    dest: ~/.bashrc
    content: "source <(starship init bash --print-full-init)"

- name: .zshrc
  copy:
    dest: ~/.zshrc
    content: "source <(starship init zsh --print-full-init)"

# - name: .hushlogin
#   copy:
#     dest: ~/.hushlogin
#     content: ""

- name: .gitconfig
  file:
    src: ~/.config/.gitconfig
    dest: ~/.gitconfig
    state: link

# - name: .tool-versions
#   file:
#     src: ~/.config/.tool-versions
#     dest: ~/.tool-versions
#     state: link
#

- name: scripts
  file:
    src: ~/.dotfiles/scripts
    dest: ~/.scripts
    state: link

# - name: .ssh/config
#   copy:
#     src: ~/.config/.ssh.config
#     dest: ~/.ssh/config
#     mode: u=rw,o=,g=

# - name: .ssh/config/control
#   file:
#     path: ~/.ssh/control
#     state: directory
#     mode: u=rwx,o=,g=
#
# - name: .Xresources
#   file:
#     src: ~/.config/.Xresources
#     dest: ~/.Xresources
#     state: link
#
# - name: gpg-agent.conf
#   copy:
#     dest: ~/.gnupg/gpg-agent.conf
#     content: "pinentry-program /bin/pinentry"
