#!/usr/bin/env bash

HOME_DIR=/home/oacs
# lua lsp
LUA_LSP="$HOME_DIR/local/lua-language-server"
if [ ! -d "$LUA_LSP" ]
then
        # clone project
        git clone  --depth=1 https://github.com/sumneko/lua-language-server $LUA_LSP
        cd lua-language-server
        git submodule update --depth 1 --init --recursive
fi

sudo npm i -g eslint_d @fsouza/prettierd

# shfmt for shell
go install mvdan.cc/sh/v3/cmd/shfmt@latest
