#!/usr/bin/env bash

HOME_DIR=/home/oacs
LOCAL_DIR=$HOME_DIR"/local"
LUA_LSP_DIR=$LOCAL_DIR"/lua-language-server"

sudo npm install -g graphql-language-service-cli vscode-langservers-extracted typescript-language-server vls 

# clone project
git clone  --depth=1 https://github.com/sumneko/lua-language-server $LUA_LSP_DIR
cd $LUA_LSP_DIR
git submodule update --depth 1 --init --recursive
cd 3rd/luamake
./compile/install.sh
cd ../..
./3rd/luamake/luamake rebuild
