#!/usr/bin/env bash

PERSONAL_SESSION="oacs"
DOTFILE="~/dotfiles"
WORKSPACE="~/workspace"
QA="$WORKSPACE/QA"
ACCOUNT_SERVICE="$WORKSPACE/account-service"
BACKEND="$WORKSPACE/backend"
BI_SERVICE="$WORKSPACE/bi-service"
BUILDFRONTENDTRANSLATIONS="$WORKSPACE/buildFrontendTranslations"
DOCKER_COMPOSE="$WORKSPACE/docker-compose"
FRONTEND="$WORKSPACE/frontend"
LOCATION_SERVICE="$WORKSPACE/location-service"
NOTIFICATION_SERVICE="$WORKSPACE/notification-service"
PREORDER_SERVICE="$WORKSPACE/preorder-service"
SEARCH_SERVICE="$WORKSPACE/search-service"
SHARED_INFRASTRUCTURE_SERVICES="$WORKSPACE/shared-infrastructure-services"
WEB_UI_COMPONENTS="$WORKSPACE/web-ui-components"

createWindow() {
    session=$1
    window=$2
    shift
    shift
    hasWindow=$(tmux list-windows -t $session | grep "$window")
    if [ -z "$hasWindow" ]; then
        cmd="tmux neww -t $session: -n $window -d"
        if [ $# -gt 0 ]; then
            cmd="$cmd $@"
        fi
        echo "Creating Window(\"$hasWindow\"): $cmd"
        eval $cmd
    fi
}

createSession() {
    session=$1
    window=$2
    shift
    shift
    cmd="tmux new -s $session -d -n $window $@"

    echo "Creating Session: $cmd"
    eval $cmd
}

attachSession() {
    session=$1
    eval "tmux attach -t $session"
}

createSession fcloud workspace -c $WORKSPACE
createWindow fcloud QA -c $QA
createWindow fcloud account-c $ACCOUNT_SERVICE
createWindow fcloud backend -c $BACKEND
createWindow fcloud bi-c $BI_SERVICE
createWindow fcloud translations -c $BUILDFRONTENDTRANSLATIONS
createWindow fcloud docker $DOCKER_COMPOSE
createWindow fcloud frontend -c $FRONTEND
createWindow fcloud location -c $LOCATION_SERVICE
createWindow fcloud notification -c $NOTIFICATION_SERVICE
createWindow fcloud preorder -c $PREORDER_SERVICE
createWindow fcloud search -c $SEARCH_SERVICE
createWindow fcloud shared_infrastructure_services -c $SHARED_INFRASTRUCTURE_SERVICES
createWindow fcloud webuicomponents -c $WEB_UI_COMPONENTS

attachSession fcloud


done
