- name: Download Nerd Fonts
  include_tasks: download.yml
  loop:
    - FiraCode
    - DejaVuSansMono
    - JetBrainsMono
    - FantasqueSansMono
    - VictorMono
    - SourceCodePro
    - Hack

- name: install fonts
  become: true
  dnf:
    name:
      - google-roboto-fonts
